name:  Dev to staging and model promotion

on:
  push:
    branches:
      - staging

env:
  MODEL_NAME: ToyotaStockPredictor
  MODEL_STAGE: Staging
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  MAE_THRESHOLD: "5.0"

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest httpx dvc dvc-s3 pandas scikit-learn mlflow

      - name: Run all tests
        run: |
          python -m pytest tests/ -v

      - name: 2. Pull Tracked Data (DVC)
        # Pulls the exact data version needed for training 
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ env.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ env.DAGSHUB_TOKEN }}
          dvc pull

      - name: Train and register candidate model
        # Fulfills Steps 1 & 2 of the Required Flow 
        id: train_model
        run: |
          python ml/train.py > train_output.json
          cat train_output.json

      - name: Deploy automatically to staging
        run: |
          echo "Building and deploying application to Staging environment..."
          curl -X POST ${{ secrets.ENDER_STAGING_WEBHOOK }}

      - name: Run Automated Quality Gates
        # run automated quality gates and  if gates pass promote model to production stage 
        run: |
          # Pipe the output from the training script directly into the evaluation script
          cat train_output.json | python ml/eval.py