import pytest
import json
import subprocess
import sys
import pandas as pd
from fastapi.testclient import TestClient
from unittest.mock import patch
from backend.app import app


class DummyPyfuncModel:
    """A mock MLflow model that strictly checks if it receives a Pandas DataFrame."""
    def predict(self, model_input):
        if isinstance(model_input, pd.DataFrame):
            return [160.50]
        raise TypeError("Model input must be a pandas DataFrame")

@patch("backend.app.mlflow.pyfunc.load_model")
def test_api_model_integration(mock_load_model):
    """Test that the API correctly integrates with MLflow's pyfunc interface."""
    # Tell the mock to return our DummyPyfuncModel
    mock_load_model.return_value = DummyPyfuncModel()
    
    # Using 'with TestClient' triggers the FastAPI 'lifespan' startup event,
    # which executes the model loading logic just like in production.
    with TestClient(app) as test_client:
        payload = {
            "Open": 150.0,
            "High": 160.0,
            "Low": 145.0,
            "Volume": 1200000
        }
        
        response = test_client.post("/predict", json=payload)
        
        # If the API didn't convert the JSON to a DataFrame, this would fail.
        assert response.status_code == 200
        assert response.json()["predicted_close_price"] == 160.50



def test_quality_gate_pipeline_integration():
    """Test the CI/CD pipeline integration between train.py and eval.py."""
    
    # Simulate the JSON output generated by train.py
    mock_train_output = json.dumps({
        "run_id": "test_run_123",
        "mse": 4.5,
        "mae": 2.1,
        "r2": 0.92, # A strong R2 score
        "model_version": 1
    })
    
    # Run eval.py as a subprocess piping the output just like gitHub actions will  do.
    process = subprocess.run(
        [sys.executable, "ml/eval.py"],
        input=mock_train_output,
        text=True,
        capture_output=True,
        env={"R2_THRESHOLD": "0.85", "MODEL_NAME": "ToyotaTest"} 
    )
    print("Eval.py stdout:", process.stdout)
    
    assert process.returncode == 0
    
    eval_result = json.loads(process.stdout.strip())
    assert eval_result["passed"] is True
    assert eval_result["mae"] == 2.1
    assert eval_result["model_version"] == 1